name: "nixos-services-options.json"
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v26
      with:
        nix_path: nixpkgs=channel:nixos-23.11
    - name: Generate JSON
      run: |
        ./scripts/generate-services-options-json.sh > nixos-services-options.json
    - name: Commit and push if it's not up-to-date
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add nixos-services-options.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update nixos-services-options.json"
        git push
